/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.doctor.apigateway.client.doctor.api;

import java.time.LocalDate;
import com.bytatech.ayoos.doctor.apigateway.client.doctor.model.DoctorDTO;
import com.bytatech.ayoos.doctor.apigateway.client.doctor.model.ReservedSlot;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-09-23T16:09:16.109+05:30[Asia/Kolkata]")

@Api(value = "DoctorResource", description = "the DoctorResource API")
public interface DoctorResourceApi {

    @ApiOperation(value = "createDoctor", nickname = "createDoctorUsingPOST", notes = "", response = DoctorDTO.class, tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = DoctorDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/doctors",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<DoctorDTO> createDoctorUsingPOST(@ApiParam(value = "doctorDTO" ,required=true )  @Valid @RequestBody DoctorDTO doctorDTO);


    @ApiOperation(value = "deleteDoctor", nickname = "deleteDoctorUsingDELETE", notes = "", tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/doctors/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteDoctorUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllDoctors", nickname = "getAllDoctorsUsingGET", notes = "", response = DoctorDTO.class, responseContainer = "List", tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = DoctorDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/doctors",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<DoctorDTO>> getAllDoctorsUsingGET(@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "getDoctor", nickname = "getDoctorUsingGET", notes = "", response = DoctorDTO.class, tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = DoctorDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/doctors/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<DoctorDTO> getDoctorUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getReservedslot", nickname = "getReservedslotUsingGET", notes = "", response = ReservedSlot.class, responseContainer = "List", tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ReservedSlot.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/reservedSlot/{profileName}/{date}",
        produces = "*/*", 
        method = RequestMethod.GET)
    Set<ReservedSlot> getReservedslotUsingGET(@ApiParam(value = "date",required=true) @PathVariable("date") LocalDate date,@ApiParam(value = "profileName",required=true) @PathVariable("profileName") String profileName);


    @ApiOperation(value = "searchDoctors", nickname = "searchDoctorsUsingGET", notes = "", response = DoctorDTO.class, responseContainer = "List", tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = DoctorDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/doctors",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<DoctorDTO>> searchDoctorsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "setBusySessions", nickname = "setBusySessionsUsingGET", notes = "", tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/{profileName}/{date}",
        method = RequestMethod.GET)
    ResponseEntity<Void> setBusySessionsUsingGET(/*@ApiParam(value = "date",required=true)*/ @PathVariable("date") String date,@ApiParam(value = "profileName",required=true) @PathVariable("profileName") String profileName);


    @ApiOperation(value = "updateDoctor", nickname = "updateDoctorUsingPUT", notes = "", response = DoctorDTO.class, tags={ "doctor-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = DoctorDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/doctors",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<DoctorDTO> updateDoctorUsingPUT(@ApiParam(value = "doctorDTO" ,required=true )  @Valid @RequestBody DoctorDTO doctorDTO);

}
